# Generated by Django 4.0.4 on 2022-06-05 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('name', models.CharField(default='', max_length=64, primary_key=True, serialize=False, verbose_name='支行名')),
                ('city', models.CharField(default='', max_length=64, verbose_name='所在城市')),
                ('assets', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='资产')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('no', models.CharField(default='', max_length=10, primary_key=True, serialize=False, verbose_name='账户号')),
                ('account_type', models.IntegerField(choices=[(0, 'Deposit'), (1, 'Cheque')], default=0, verbose_name='账户类型')),
                ('open_date', models.DateField(auto_now_add=True, verbose_name='开户日期')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='余额')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('overdraft', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='透支额')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BankSystem.branch', verbose_name='开户支行')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(default='', max_length=18, primary_key=True, serialize=False, verbose_name='客户身份证号')),
                ('name', models.CharField(default='', max_length=64, verbose_name='姓名')),
                ('phone', models.CharField(default='', max_length=11, verbose_name='电话号码')),
                ('address', models.CharField(default='', max_length=256, verbose_name='住址')),
                ('principal_type', models.IntegerField(choices=[(0, 'Account'), (1, 'Loan'), (2, 'Both')], default=0, verbose_name='负责类型')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('no', models.CharField(default='', max_length=10, primary_key=True, serialize=False, verbose_name='部门号')),
                ('name', models.CharField(default='', max_length=64, verbose_name='部门名称')),
                ('type', models.CharField(default='', max_length=64, verbose_name='部门类型')),
                ('manager_id', models.CharField(default='', max_length=18, verbose_name='经理身份证号')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('no', models.CharField(default='', max_length=10, primary_key=True, serialize=False, verbose_name='账户号')),
                ('account_type', models.IntegerField(choices=[(0, 'Deposit'), (1, 'Cheque')], default=0, verbose_name='账户类型')),
                ('open_date', models.DateField(auto_now_add=True, verbose_name='开户日期')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='余额')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('interest_rate', models.FloatField(default=1.0, verbose_name='利率')),
                ('currency_type', models.CharField(default='', max_length=3, verbose_name='货币类型')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BankSystem.branch', verbose_name='开户支行')),
                ('customers', models.ManyToManyField(to='BankSystem.customer', verbose_name='关联客户')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='BankSystem.customer')),
                ('name', models.CharField(default='', max_length=64, verbose_name='姓名')),
                ('phone', models.CharField(default='', max_length=11, verbose_name='电话号码')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱地址')),
                ('relationship', models.CharField(default='', max_length=256, verbose_name='与客户的关系')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.CharField(default='', max_length=18, primary_key=True, serialize=False, verbose_name='员工身份证号')),
                ('name', models.CharField(default='', max_length=64, verbose_name='姓名')),
                ('phone', models.CharField(default='', max_length=11, verbose_name='电话号码')),
                ('address', models.CharField(default='', max_length=256, verbose_name='住址')),
                ('start_date', models.DateField(default='2022-5-16', verbose_name='开始工作日期')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BankSystem.department', verbose_name='所属部门')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('no', models.CharField(default='', max_length=10, primary_key=True, serialize=False, verbose_name='贷款号')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='总金额')),
                ('status', models.CharField(default='未开始发放', max_length=64, verbose_name='贷款状态')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BankSystem.branch', verbose_name='贷款支行')),
                ('customers', models.ManyToManyField(to='BankSystem.customer', verbose_name='关联客户')),
            ],
        ),
        migrations.CreateModel(
            name='Deposit_Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_access_date', models.DateTimeField(auto_now=True, verbose_name='最近访问时间')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BankSystem.customer')),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BankSystem.deposit')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BankSystem.staff', verbose_name='负责人'),
        ),
        migrations.CreateModel(
            name='Cheque_Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_access_date', models.DateTimeField(auto_now=True, verbose_name='最近访问时间')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('cheque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BankSystem.cheque')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BankSystem.customer')),
            ],
        ),
        migrations.AddField(
            model_name='cheque',
            name='customers',
            field=models.ManyToManyField(to='BankSystem.customer', verbose_name='关联客户'),
        ),
    ]
