# Generated by Django 4.0.4 on 2022-06-05 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BankSystem', '0002_payout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payout',
        ),
    ]
